releaseDate:
  2022-04-19

changeLog:
  - 新增 油站支付收银台
  - 新增 加油指引
  - 新增 什么是加油省钱卡
  - 新增 运营活动多弹窗
  - 新增 新手任务弹窗
  - 新增 接口环境切换
  - 新增 补贴奖励领取流程介绍
  - 新增 加油补贴
  - 新增 厦门国际银行服务协议
  - 新增 银行路由
  - 新增 加油省钱卡开户支持银行
  - 优化 加油省钱卡规则
  - 优化 加油列表
  - 优化 默认渠道码
  - 优化 油站列表错误处理
  - 修复 油站详情价格显示异常
  - 修复 其他已知的问题

historyChangeLog:
  7.8.3:
    - 新增 授权登录
    - 新增 更新日志
    - 优化 港澳油站
    - 优化 立即充值逻辑
    - 优化 银联付款码支付
    - 优化 未登录路由跳转
    - 修复 其他已知的问题
  7.8.2:
    - 新增 银联付款码支付
    - 新增 设置中心
    - 新增 找回银联支付密码
    - 新增 清除缓存
    - 优化 加油页活动运营位
    - 优化 登录落地页
    - 优化 首页活动运营位
    - 优化 银联绑卡流程
    - 优化 支付方式
    - 优化 用户体验
    - 修复 已知bug
  7.8.1:
    - 新增 加油充值
    - 新增 问题反馈
    - 新增 我的红包
    - 新增 登录落地页
    - 新增 引导充值广告语
    - 优化 充值页运营位
    - 优化 未收录油站逻辑
    - 优化 统一底部按钮
    - 优化 其他样式
    - 优化 用户体验
    - 修复 其他已知的漏洞
  7.7.9:
    - 新增 快捷加油
    - 新增 银联付款码
    - 新增 卡券兑换
    - 优化 用户体验
    - 修复 其他已知的漏洞
  7.7.8:
    - 新增 客服中心
    - 新增 我的卡号
    - 新增 港澳油站
    - 新增 油站搜索
    - 优化 用户体验
    - 修复 IOS输入框不能输入的问题
    - 修复 IOS下的样式的问题
    - 修复 微信下复制失败的问题
    - 修复 其他已知的漏洞
