interface OrderListData {
  accountBalance: number
  bankName: string
  bankNo: string
  bankProxy: null
  canContinuePay: false
  canRefund: false
  canReimburse: false
  cancelTime: string
  cashBackReceiveStatus: null
  cashierUrlParams: null
  channelId: number
  channelName: string
  createDateStr: string
  createTime: string
  createTimestamp: number
  deleteFlag: number
  extendJson: null
  gunName: null
  hzType: null
  id: number
  lat: number
  literNum: null
  lng: number
  matchedConsumedNo: null
  memberId: number
  merchantId: null
  mobile: string
  noCashBackReason: null
  oilId: number
  oilName: string
  orderAmount: number
  orderNo: string
  orderStatus: string | null
  payAmount: null
  payByThirdBank: string
  payStatus: string
  payStatusStr: string
  payTime: null
  payWay: string
  redEnvelopAmount: null
  redEnvelopReceiveStatus: null
  reduceAmount: null
  refuelcorpOrderAuditInfo: null
  refuelcorpOrderInfo: null
  refundInfo: null
  remainingTime: number
  remark: string
  stationAddress: null
  stationId: number
  stationName: string
  stationType: null
  stationTypeStr: string
  thirdOrderNo: null
  totalSaveAmount: number
  updateTime: string
  vipReduceAmount: null
}

interface OrderDetailData {
  accountBalance: number
  bankName: string
  bankNo: string
  bankProxy: null
  canContinuePay: false
  canRefund: false
  canReimburse: false
  cancelTime: null
  cashBackReceiveStatus: null
  cashierUrlParams: null
  channelId: number
  channelName: string
  createDateStr: string
  createTime: string
  createTimestamp: number
  deleteFlag: number
  extendJson: null
  gunName: string
  hzType: string
  id: number
  lat: number
  literNum: number
  lng: number
  matchedConsumedNo: null
  memberId: number
  merchantId: null
  mobile: string
  noCashBackReason: null
  oilId: number
  oilName: string
  orderAmount: number
  orderNo: string
  orderStatus: string
  payAmount: string
  payByThirdBank: string
  payStatus: string
  payStatusStr: string
  payTime: string
  payWay: null
  redEnvelopAmount: null
  redEnvelopReceiveStatus: null
  reduceAmount: number
  refuelcorpOrderAuditInfo: null
  refuelcorpOrderInfo: null
  refundInfo: null
  remainingTime: number
  remark: string
  stationAddress: string
  stationId: number
  stationName: string
  stationType: number
  stationTypeStr: string
  thirdOrderNo: null
  totalSaveAmount: number
  updateTime: string
  vipReduceAmount: null
}
